# Generated by Django 2.2.5 on 2020-12-24 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=255, verbose_name='CNPJ')),
                ('name', models.CharField(max_length=200, verbose_name='Apelido da Instituição')),
                ('code', models.CharField(max_length=200, verbose_name='Código')),
                ('year', models.IntegerField()),
                ('active', models.NullBooleanField(verbose_name='Ativo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation', models.CharField(choices=[('Abertura de Segmento', 'Abertura de Segmento'), ('Página Exclusiva', 'Página Exclusiva'), ('Contra Capa', 'Contra Capa'), ('Ipanema', 'Ipanema')], max_length=100, verbose_name='Participação')),
                ('segment', models.CharField(blank=True, choices=[('Administradores', 'Administradores'), ('Advogados', 'Advogados'), ('Agentes Fiduciários', 'Agentes Fiduciários'), ('Auditores', 'Auditores'), ('Avaliadores e Classificadoras', 'Avaliadores e Classificadoras'), ('Consultores', 'Consultores'), ('Custodiantes', 'Custodiantes'), ('Distribuidores', 'Distribuidores'), ('Estruturadores', 'Estruturadores'), ('Fintechs', 'Fintechs'), ('Gestores', 'Gestores'), ('Informação e Análise', 'Informação e Análise'), ('Investidores Institucionais', 'Investidores Institucionais'), ('Securitizadoras', 'Securitizadoras'), ('Servicers e Agentes de Cobrança', 'Servicers e Agentes de Cobrança'), ('Tecnologia da Informação', 'Tecnologia da Informação'), ('Lawtechs', 'Lawtechs'), ('Seguradoras', 'Seguradoras'), ('Infraestrutura de Mercado', 'Infraestrutura de Mercado'), ('', '')], max_length=100, verbose_name='Segmento')),
                ('condition', models.CharField(choices=[('Pagante', 'Pagante'), ('Cortesia', 'Cortesia')], max_length=50, verbose_name='Condição')),
                ('layout', models.NullBooleanField(verbose_name='Layout')),
                ('layoutuqbar', models.NullBooleanField(verbose_name='Layout UQBAR')),
                ('status', models.CharField(choices=[('Não Iniciado', 'Não Iniciado'), ('Incompleto', 'Incompleto'), ('Concluído', 'Concluído'), ('Aprovado', 'Aprovado')], default='Não Iniciado', max_length=50, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client', verbose_name='Cliente')),
            ],
        ),
    ]
