# Generated by Django 2.2.5 on 2020-12-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_client_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='participation',
            field=models.CharField(choices=[('Página Exclusiva', 'Página Exclusiva'), ('Contra Capa', 'Contra Capa'), ('Ipanema', 'Ipanema')], max_length=100, verbose_name='Participação'),
        ),
    ]
