# Generated by Django 2.2.5 on 2020-12-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201224_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='participation',
            field=models.CharField(choices=[('Abertura de Segmento', 'Abertura de Segmento'), ('Página Exclusiva', 'Página Exclusiva'), ('Contra Capa', 'Contra Capa'), ('Ipanema', 'Ipanema')], max_length=100, verbose_name='Participação'),
        ),
    ]
